# numpy practice session

In [ ]:
#pip install numpy

In [1]:
# import this library in j.notebook
import numpy as np

# creating an array using numpy

In [4]:
food = np.array(["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [5]:
price = np. array([5, 5, 5])
price

array([5, 5, 5])

In [7]:
type(price)

numpy.ndarray

In [8]:
type(food)

numpy.ndarray

In [10]:
len(food)

3

In [13]:
price[0:]

array([5, 5, 5])

In [16]:
food[1]

'samosa'

In [17]:
price.mean()

5.0

In [20]:
# zero
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [21]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [23]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# specify
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [26]:
# specific interval
np. arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
# table of 5
np.arange(5, 55, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [37]:
# line space
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [40]:
# specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [41]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array functions

In [43]:
a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [44]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [45]:
b = np.array([10.2,3.4,53.6,91.6,45.5])
b

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [47]:
c = np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.6,  45.5])

In [48]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  45.5,  53.6,  91.6, 100. , 320. ])

# 2-D arrays

In [64]:
x = np. array([[1,2], [5,4]])
x

array([[1, 2],
       [5, 4]])

In [60]:
y = np.array([[6,7], [7,8]])
y

array([[6, 7],
       [7, 8]])

In [68]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [5, 4],
       [6, 7],
       [7, 8]])

In [69]:
np.concatenate((x,y), axis=1)

array([[1, 2, 6, 7],
       [5, 4, 7, 8]])

In [70]:
a = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                         
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [72]:
# to find the number of dimension
a.ndim

3

In [76]:
type(a)

numpy.ndarray

In [74]:
b = np.array([[5,6,7],
             [8,9,10],
             [10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [75]:
b.ndim

2

In [77]:
#size (number of elements)
a.size

24

In [79]:
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [78]:
#shape
a.shape

(3, 2, 4)

In [84]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
# reshape
b= a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
# reshape
np.reshape(a, newshape=(1, 9), order='c')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [89]:
# covert 1D into 2D
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
a.shape

(9,)

In [91]:
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [92]:
b.shape

(1, 9)

In [93]:
#column wise
c = a[: , np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [95]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [97]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [98]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [99]:
a.sum()

45

In [120]:
a.mean()

5.0